POST http://localhost:8888/api/blogs/
Content-Type: application/json

{
    "title": "1191study, day day up",
    "author": "number one",
    "url": "https://fullstackopen.com/en/part3/node_js_and_express",
    "likes": 1
}